/*
 * Copyright (c) 2008-2016 Computer Network Information Center (CNIC), Chinese Academy of Sciences.
 * 
 * This file is part of Duckling project.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License. 
 *
 */
/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package cn.vlabs.duckling.vwb.ui.action;

import java.io.IOException;
import java.io.Writer;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import cn.vlabs.duckling.vwb.ui.base.BaseAction;

/**
 * Dylan Creation date: 07-26-2010
 * 
 * XDoclet definition:
 * 
 * @struts.action validate="true"
 */
//TODO 修改CLB API 至 CLB 6.0.1，图片簿需重新设计
public class ImgScrServiceAction extends BaseAction {
//	private static String BASE_URL = "attach/";
//	private static final String[] c_externalImg = { "jpg", "jpeg", "gif", "png", "bmp" };

//	private boolean accept(FolderInfo f, String strfilter) {
//		strfilter = strfilter.toLowerCase();
//		strfilter = strfilter.replace("*", "");
//		try {
//			String tmp = f.name.toLowerCase();
//			if ("".equals(strfilter) || ".".equals(strfilter)) {
//				if (f.isFile) {
//					for (int i = 0; i < c_externalImg.length; i++) {
//						if (tmp.endsWith(c_externalImg[i]))
//							return true;
//					}
//				}
//			} else if (tmp.endsWith(strfilter)) {
//				return true;
//			}
//			return false;
//		} catch (Exception e) {
//			return false;
//
//		}
//	}
//
//	private void getscriptbyclb(StringBuffer str, String imgpath,
//			HttpServletRequest request) {
//		Site site = VWBSite.findSite(request);
//		String baseurl = site.getBaseURL();
//		String[] imgpatharr = imgpath.split("/");
//		String clbpath = imgpatharr[0];
//		String filter = imgpatharr[1];
//		VWBContext context = VWBContext.createContext(request,
//				VWBCommand.ATTACH, null);
//		AttachmentService attachementService = site.getAttachmentService();
//		List<FolderInfo> results = new ArrayList<FolderInfo>();
//		FolderInfo[] files = null;
//		String vo_id = site.getProperty(KeyConstants.SITE_UMT_VO_KEY);
//		files = attachementService.folderList(context.getVWBSession(),
//				"/vo/" + vo_id + "/" + clbpath, BASE_URL);
//		for (FolderInfo f : files) {
//			if (accept(f, filter))
//				results.add(f);
//		}
//
//		for (int i = 0; i < results.size(); i++) {
//			String hashid = AccessCLBHelper.getHashId(results.get(i).name,
//					results.get(i).docid + "", BASE_URL);
//			String lastUpdate = files[i].lastUpdate;
//			String ver = "?ver=" + lastUpdate;
//			if (i + 1 != results.size())
//				str.append("\"" + baseurl + "/" + hashid + ver + "\",");
//			else
//				str.append("\"" + baseurl + "/" + hashid + ver + "\"");
//		}
//	}

	/**
	 * @param mapping
	 * @return
	 */
	private ActionForward opendialog(ActionMapping mapping,
			HttpServletRequest request) {
//		VWBContext vwbcontext = VWBContext.createContext(request,
//				VWBCommand.ATTACH, null);
//		Site site = vwbcontext.getSite();
//		VWBSession vwbsession = vwbcontext.getVWBSession();

//		AttachmentService attachementService = site.getAttachmentService();
		List<String> results = new ArrayList<String>();

//		FolderInfo[] files = attachementService.folderList(vwbsession,
//				"/vo/" + site.getProperty(KeyConstants.SITE_UMT_VO_KEY),
//				BASE_URL);
//		for (FolderInfo f : files) {
//			results.add(f.name);
//		}
		request.setAttribute("results", results);
		return mapping.findForward("ok");
	}

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {

		String strType = request.getParameter("type");
		if ("open".equals(strType)) {
			return opendialog(mapping, request);
		}else{
			String strpathes = request.getParameter("path");
			String[] pathes = strpathes.split("\\|");
			StringBuffer str = new StringBuffer();
			for (String strarr : pathes) {
				String[] arr = strarr.split(":");
				String id = arr[0];
//				String imgpath = arr[1];
				str.append("var " + id + "=[");
//				getscriptbyclb(str, imgpath, request);
				str.append("];\n");
	
			}
			response.setContentType("text;charset=UTF-8");
			try {
				Writer wr = response.getWriter();
				wr.write(str.toString());
				wr.close();
			} catch (IOException e) {
			}
			return null;
		}
	}
}