/*
 * Copyright (c) 2008-2016 Computer Network Information Center (CNIC), Chinese Academy of Sciences.
 * 
 * This file is part of Duckling project.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License. 
 *
 */
/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package cn.vlabs.duckling.vwb.ui.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.upload.FormFile;

/**
 * Introduction Here.
 * 
 * @date Feb 25, 2010
 * @author Sun Peng (sunp@cnic.cn)
 */
public class SkinForm extends ActionForm {
	private static final long serialVersionUID = 1L;
	/** skinname property */
	private String skinname;
	private String template;
	private boolean shared;
	/** method property */
	private String method;
	
    private FormFile file;
	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
        
	    return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the skinname.
	 * @return String
	 */
	public String getSkinname() {
		return skinname;
	}

	/** 
	 * Set the skinname.
	 * @param skinname The skinname to set
	 */
	public void setSkinname(String skinname) {
		this.skinname = skinname;
	}
	public void setShared(boolean shared){
		this.shared=shared;
	}
	public boolean isShared(){
		return this.shared;
	}
	/** 
	 * Returns the method.
	 * @return String
	 */
	public String getMethod() {
		return method;
	}

	/** 
	 * Set the method.
	 * @param method The method to set
	 */
	public void setMethod(String method) {
		this.method = method;
	}

    public void setFile(FormFile file)
    {
        this.file = file;
    }

    public FormFile getFile()
    {
        return file;
    }

	public String getTemplate() {
		return template;
	}

	public void setTemplate(String template) {
		this.template = template;
	}
    
    
}