/*
 * Copyright (c) 2008-2016 Computer Network Information Center (CNIC), Chinese Academy of Sciences.
 * 
 * This file is part of Duckling project.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License. 
 *
 */
/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package cn.vlabs.duckling.vwb.ui.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 08-27-2007
 * 
 * XDoclet definition:
 * @struts.form name="searchCLBForm"
 */
public class StasticsAlllikeUserForm extends ActionForm {
	/*
	 * Generated Methods
	 */

    private static final long serialVersionUID = 1L;  

    /** pattern property */
    private String starttime;
    private String endtime;
    
    
    public StasticsAlllikeUserForm() {
        //field=AUTHOR; 
    }
    
    /*
     * Generated Methods
     */

    /** 
     * Method validate
     * @param mapping
     * @param request
     * @return ActionErrors
     */
    public ActionErrors validate(ActionMapping mapping,
            HttpServletRequest request) {
        // TODO Auto-generated method stub
        return null;
        //return null;
    }
    
        
    /** 
     * Method reset
     * @param mapping
     * @param request
     */
    public void reset(ActionMapping mapping, HttpServletRequest request) {
        // TODO Auto-generated method stub
        //this.field=AUTHOR;
        this.starttime=null;        
        this.endtime=null;
    }

    /**
     * Returns the pattern.
     * 
     * @return String
     */
    public String getStartTime() {
        return starttime;
    }

    public void setStartTime(String time) {
        this.starttime = time;
    }

    public String getEndTime() {
        return endtime;
    }

    public void setEndTime(String time) {
        this.endtime = time;
    }
   
}