/*
 * Copyright (c) 2008-2016 Computer Network Information Center (CNIC), Chinese Academy of Sciences.
 * 
 * This file is part of Duckling project.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License. 
 *
 */
/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package cn.vlabs.duckling.vwb.ui.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 05-19-2010
 * 
 * XDoclet definition:
 * @struts.form name="subscribeForm"
 */
public class SubscribeForm extends ActionForm {
	private static final long serialVersionUID = 1L;

	/** rec_time property */
	private String hour;

	/** emails property */
	private String emails;

	/** pageName property */
	private String pageName;
	private String page;
	private String act;
	private int deleteESubId;
	/*
	 * Generated Methods
	 */


	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		hour=null;
		emails=null;
		pageName=null;
		deleteESubId=0;
	}

	/** 
	 * Returns the hour.
	 * @return int
	 */
	public String getHour() {
		return hour;
	}

	/** 
	 * Set the rec_time.
	 * @param hour The rec_time to set
	 */
	public void setHour(String hour) {
		this.hour = hour;
	}

	/** 
	 * Returns the emails.
	 * @return String
	 */
	public String getEmails() {
		return emails;
	}

	/** 
	 * Set the emails.
	 * @param emails The emails to set
	 */
	public void setEmails(String emails) {
		this.emails = emails;
	}

	/** 
	 * Returns the pageName.
	 * @return String
	 */
	public String getPageName() {
		return pageName;
	}

	/** 
	 * Set the pageName.
	 * @param pageName The pageName to set
	 */
	public void setPageName(String pageName) {
		this.pageName = pageName;
	}

	public void setAct(String method) {
		this.act = method;
	}

	public String getAct() {
		return act;
	}

	public void setDeleteESubId(int deleteESubId) {
		this.deleteESubId = deleteESubId;
	}

	public int getDeleteESubId() {
		return deleteESubId;
	}
	public void setPage(String page){
		this.page=page;
	}
	public String getPage() {
		return page;
	}
}